### ISSUE TITLE
投稿: Windows下使用Linux shell脚本绘制GMT图

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#136]
https://mp.weixin.qq.com/s?__biz=MzI1MDMzNzAzOA==&mid=100000012&idx=1&sn=1797406e8bc7eab0d548804a46213ce5&chksm=6982836d5ef50a7b70dbfe12a78e8257ad300116a3e3ee2acf7e645a8923eb811751b58d8146&mpshare=1&scene=23&srcid=0221qQWtLESH4x3uQnkxjk5l&sharer_sharetime=1582342989406&sharer_shareid=e4f35d194599b3b30020a3d677b945c4#rd

**Comment by core-man** [comment]
Transfer it to GMT_Docs?
