### ISSUE TITLE
投稿: “中国大地构造单元划分“数据数字化

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#137]
![image](https://user-images.githubusercontent.com/3974108/75085960-98c8a700-54fc-11ea-97f5-9922effe56b1.png)

**Comment by core-man** [comment]
Transfer it to GMT_Docs?

**Comment by seisman** [comment]
I actually don't remember what it means. I think we should close it because:

1. currently we don't have the digitalized data
2. none of us need it, so none of us will try to digitalize it

**Comment by core-man** [comment]
Sounds good.
