### ISSUE TITLE
使用微信公众号？

### ISSUE THREAD

**Issue by core-man** [gmt-china/gmt-china.org#153]
我理解的社区网站是门户，所有东西汇总的地方。手册是根本性的学习资料。但是宣传和新闻，还是要需要编辑方便、及时通讯、受众广泛的网络工具，现在看微信公众号比较合适。当然也许以后可以使用其他工具，我们也不需要维护公众号的历史内容。

**Comment by seisman** [comment]
暂时没想到有什么东西需要放到公众号里的。而且公众号里的文章发布后是不能修改的。

**Comment by liuzhumei** [comment]
公众号更多的是宣传作用，适合放的文章列表比如：

1. GMT6.2.0rc 发布 
2. 视频教程更新 
2. 2019版行政区划数据更新 
3. 社区培训或团建（将来还有吗？）
4. new examples 

其中前三条更新频率不高，第四条完全可以吸纳让现在的优秀勤快的小青年们参加，保持周更，我觉得可行性蛮大的。
总之，赞同搞。

**Comment by core-man** [comment]
> 暂时没想到有什么东西需要放到公众号里的。

我觉得以上内容就可以

> 而且公众号里的文章发布后是不能修改的。

公众号里的文章发布后也不需要修改吧，只是一个发布和宣传工具。发布的核心内容在社区网站或手册中，公众号只是简短概括，上图，给链接即可。

**Comment by seisman** [comment]
我个人对公众号没多大兴趣，但是我不反对。

**Comment by core-man** [comment]
我比较支持建立公众号，这样有利于社区的建设和传播。但是我个人没有精力去帮助维护和管理公众号，重心还是在于维护文档和各仓库。 @liuzhumei 如果目前只有你一个人有经验和可能有精力去维护公众号的话，可以暂时不建立。 Ping @CovMat @wangliang1989 for comments or help.

**Comment by wangliang1989** [comment]
可有可无
