### ISSUE TITLE
Update contribution guide

### ISSUE THREAD

**Issue by core-man** [gmt-china/gmt-china.org#155]
- https://github.com/gmt-china/gmt-china.org/wiki
- https://github.com/gmt-china/gmt-china.org/blob/master/CONTRIBUTING.md
- https://gmt-china.org/blog/instructions-for-authors/

**Comment by seisman** [comment]
最近一段时间，社区主页的主要改动在于，删除了所有示例，博客中仅保留GMT相关新闻、社区相关新闻以及其他不适合放在中文手册中的内容。在这一改版之后，社区主页将只接收新闻的投稿。

关于以上三个贡献指南，我的想法如下：

> * [gmt-china/gmt-china.org/wiki](https://github.com/gmt-china/gmt-china.org/wiki)

主要介绍了github的pull request流程。这一部分与GMT无关，而且与 seismo-learn 中的指南也有大量重复，因而我不打算再维护这些内容。我们应假定用户已经掌握了 git 和 github 的使用。

> * [https://github.com/gmt-china/gmt-china.org/blob/master/CONTRIBUTING.md](https://github.com/gmt-china/gmt-china.org/blob/master/CONTRIBUTING.md?rgh-link-date=2021-05-26T08%3A24%3A50Z)

原文大部分已失效，故而已删除，部分有用的东西已经合并到现在的 README 中。

> * [gmt-china.org/blog/instructions-for-authors](https://gmt-china.org/blog/instructions-for-authors/)

这一篇博文需要做简单更新。由于社区主页已经不再接收示例投稿，所有示例应投稿到 GMT_docs 中，因为投稿示例相关的贡献指南应包含在 GMT_docs 中。这一篇博文的内容需要做简单更新。

**Comment by core-man** [comment]
> 这一篇博文需要做简单更新。由于社区主页已经不再接收示例投稿，所有示例应投稿到 GMT_docs 中，因为投稿示例相关的贡献指南应包含在 GMT_docs 中。这一篇博文的内容需要做简单更新。

Sounds good.
