### ISSUE TITLE
Build bug

### ISSUE THREAD

**Issue by core-man** [gmt-china/gmt-china.org#161]
#149 and #148 have not been built successfully due to old hugo version or theme. We may want to update hugo and theme. This will be done in several PRs.

- Migrate to GitHub Actions: #156
- Update to theme v5.2

**Comment by seisman** [comment]
I would suggest we revert the changes to image files in #148 and #149 so that at least the CI can pass before we do the migration.

**Comment by core-man** [comment]
> I would suggest we revert the changes to image files in #148 and #149 so that at least the CI can pass before we do the migration.

Sound good~

**Comment by seisman** [comment]
#148 causes troubles, not because the old hugo or theme versions. I think it's most likely because how the images are treated differently on Windows and Linux/macOS.
