### ISSUE TITLE
国界问题

### ISSUE THREAD

**Issue by PeterPanwl** [gmt-china/gmt-china.org#19]
凡是绘制了国界的，都应该注明：

本图不作领土划界依据
This figure does not make the basis for territorial delimitation

不知道你们是否赞同，还有以何种适当的形式表述
https://github.com/gmt-china/gmt-china.org/pull/20

**Comment by seisman** [comment]
1. 应该注明，但具体要如何表述，还需要进一步讨论。
2. 关于 #20 ，我建议直接使用 `-U` 选项加说明，而不是使用 `pstext`
