### ISSUE TITLE
Preview link bug

### ISSUE THREAD

**Issue by core-man** [gmt-china/gmt-china.org#193]
See https://github.com/gmt-china/gmt-china.org/pull/191#issuecomment-856555670

**Comment by seisman** [comment]
@core-man I'm not exactly sure what your comment https://github.com/gmt-china/gmt-china.org/pull/191#issuecomment-856555670 means. 

PR #183 and #197 should fix some preview-link bugs that I know. 

Please let me know if there are any other issues after these two PRs are merged.

**Comment by seisman** [comment]
@core-man Please see if we can close the issue, since preview in PR #199 seems good.
