### ISSUE TITLE
更新贡献者？

### ISSUE THREAD

**Issue by core-man** [gmt-china/gmt-china.org#211]
最早提出于 https://github.com/gmt-china/GMT_docs/pull/475#discussion_r659377518:

>> 如何与社区那个贡献者列表统一？社区那个贡献者列表应该不仅是当前的中文手册的贡献者们吧。也就是说这里的贡献者是否特指中文手册贡献者？

> 社区网站的贡献者列表包括了贡献示例的人，现在社区网站已经没有示例了，所以有些人已经可以删掉了，只保留活跃人员即可。

以及 https://github.com/gmt-china/GMT_docs/pull/475#discussion_r659489020:
> 社区弄两个分类：维护者和核心贡献者？还是现在这样核心维护者和贡献者？我比较倾向前者

**Comment by core-man** [comment]
Ping @seisman for comments.

**Comment by seisman** [comment]
在更新主题之前不想对这些东西做太多改动

**Comment by seisman** [comment]
原来的社区主页里有一个贡献者列表，类似下图：
<img width="488" alt="image" src="https://user-images.githubusercontent.com/3974108/169041594-f681a0df-5308-4336-9336-d83c1be9dffe.png">

该贡献者列表在新版中已经删除。删除的主要原因是，目前使用的模板里，需要为每个贡献者建立一个单独的页面，而且需要添加每个人的照片、单位以及各种链接信息，我觉得比较麻烦。

我目前的想法是，直接给一个到 https://github.com/orgs/gmt-china/people 的链接。

**Comment by core-man** [comment]
> 我目前的想法是，直接给一个到 https://github.com/orgs/gmt-china/people 的链接。

Sounds good.
