### ISSUE TITLE
增加评论功能

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#25]
### 想要做的事情

为社区主页、参考手册、模块手册增加评论功能

### 目的

方便用户在看文档的过程中直接指出文档中可能存在的问题，评论中不会回答 GMT 的具体问题

### 计划使用的服务

计划使用 disqus 服务，访问可能偶尔有难度，但国内似乎没有类似产品。

### 遇到的问题

社区目前的邮箱 admin@gmt-china.org 使用了腾讯企业邮箱，似乎邮箱一直收不到 disqus 的邮件，导致无法验证通过，进而无法使用 disqus 服务。

### 解决办法

1. 换用其他邮箱
2. 换用其他评论服务
3. 其他解决办法

**Comment by wangliang1989** [comment]
把麻花疼炒了

**Comment by zhaozhiyuan1989** [comment]
畅言app也可以添加评论功能，不过需要在国内的备案号。

**Comment by zhaozhiyuan1989** [comment]
具神，最近我试用 gitalk 在博客中添加评论 ，感觉还不错。可以到我的网站看看效果 <http://zhaozhiyuan.org>

**Comment by seisman** [comment]
Closed as fixed.
