### ISSUE TITLE
下载页面给出老版本的链接？

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#290]
目前下载页面长这样，只有 GMT 最新版本的下载链接。

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/3974108/168774317-cc8b2bbb-d308-457b-a666-d400392a9a87.png">

有些用户可能因为某些特殊原因需要下载老版本，这里是否要提供老版本的下载链接？

**Comment by core-man** [comment]
> 有些用户可能因为某些特殊原因需要下载老版本，这里是否要提供老版本的下载链接？

建议提供吧，或者给出去哪里找老版本？
