### ISSUE TITLE
更新 VScode 使用教程

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#305]
![0DBCA7AEB7FD4839CBF0C6DBDAA9AC92](https://user-images.githubusercontent.com/3974108/179389457-ca1a47f7-aaa8-4c16-ad63-e2ae1a0f08f8.jpg)

关于 VScode 的 code-runner 插件运行代码的问题，其实本质原因在这里有解释。视频教程以及 vscode 教程里提到的“必须在脚本目录里右键打开vscode"其实是非必须的，只需要勾选 "File Directory As Cwd" 选项就行了 

![image](https://user-images.githubusercontent.com/3974108/179389463-09640249-b44a-4de1-90e3-b51500140be7.png)

**Comment by CovMat** [comment]
这个已经改好了，可以关闭了
