### ISSUE TITLE
gdal版本差异

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#33]
gdal 目前有两个主流版本: 1.x 和 2.x。需要确认二者用法是否相同。还需要确认不同操作系统下不同版本的 gdal 是否支持 netcdf/GMT 格式。

**Comment by zhaozhiyuan1989** [comment]
之前用的华硕笔记本，Win7 系统 GDAL 2.1.0 版本，支持 GMT 格式；
今年换成惠普笔记本将之前的 GDAL 文件夹拷贝过来就不支持 GMT 格式了。。。

**Comment by seisman** [comment]
重新安装的话还支持么？

**Comment by zhaozhiyuan1989** [comment]
我用的已经编译好的版本，下载解压缩后直接添加到 PATH 后就直接可以用了。刚才我重新下载了 2.2.1 版本的，还是不支持，我都怀疑和电脑品牌有关了
