### ISSUE TITLE
中国断层数据来源

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#55]
http://gmt-china.org/example/ex007/

中国断层数据可能来自于 Qidong Deng，对应的文章为 

> Deng, Q. D., Zhang, P. Z., Ran, Y. K., Yang, X. P., Min, W., Chen, L. C., 2003. Active tectonics and earthquake activities in China (in Chinese with English abstract). Earth Science Frontiers, 10(Supplement): 66-73.

需要确认文章信息是否准确，并给出中文和英文引用的格式。

**Comment by SeisPider** [comment]
可能的中文引用：邓起东, 张培震, 冉勇康, 杨晓平, 闵伟 & 陈立春, 2003. 中国活动构造与地震活动, 地学前缘, 10(z1), 66-73.

**Comment by seisman** [comment]
The paper http://www.csi.ac.cn/manage/eqDown/25DZZJ/01_003A/AP003.pdf

**Comment by seisman** [comment]
official site: http://www.dxqy.chinajournal.net.cn/WKC/WebPublication/paperDigest.aspx?paperID=71D78A2C-B632-411A-8CE5-F9E9CDFD7B3C
