### ISSUE TITLE
在线填表功能

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#62]
http://gmt-china.org/about/ 的用户分布图需要用户将城市、单位、经纬度信息发送到邮箱。稍微有点复杂，或许可以设计一个表格，让用户可以直接在线填写并提交。

**Comment by zhaozhiyuan1989** [comment]
感觉静态网页不太好实现这个功能，你有没有具体的实现思路

**Comment by seisman** [comment]
静态网页应该实现不了，所以需要借助于外部的服务，类似于评论功能。

**Comment by zhaozhiyuan1989** [comment]
那直接添加评论功能就行了吧

**Comment by seisman** [comment]
嗯，这样也可以

**Comment by wangliang1989** [comment]
如果用评论，下面就会有不少评论，看着不舒服

**Comment by zhaozhiyuan1989** [comment]
添加之后就可以删掉了呀

**Comment by wangliang1989** [comment]
好，我不知道可以删除
