### ISSUE TITLE
示例打赏功能

### ISSUE THREAD

**Issue by seisman** [gmt-china/gmt-china.org#65]
1. 是否要开通打赏功能
2. 是打赏给个人还是作为整个社区的经费

**Comment by zhaozhiyuan1989** [comment]
支持开通打赏功能用于社区的运作

**Comment by seisman** [comment]
个人打赏功能相对容易做些，只要把作者的二维码贴上去即可，一篇博文多个作者的只考虑第一作者。

相对难办的是社区打赏功能，微信和支付宝的打赏只能给某个人，相对来说不够透明。

**Comment by wangliang1989** [comment]
也许可以注册一个单独的支付宝账号
